### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by melvinsh** [hadriansecurity/subwiz#4]
Getting the following error:

```
Traceback (most recent call last):
  File "/home/melvin/.local/bin/subwiz", line 5, in <module>
    from subwiz.cli import main
  File "/home/melvin/.local/lib/python3.9/site-packages/subwiz/__init__.py", line 1, in <module>
    from subwiz.main import run
  File "/home/melvin/.local/lib/python3.9/site-packages/subwiz/main.py", line 12, in <module>
    from subwiz.model import GPT
  File "/home/melvin/.local/lib/python3.9/site-packages/subwiz/model.py", line 160, in <module>
    class GPT(nn.Module):
  File "/home/melvin/.local/lib/python3.9/site-packages/subwiz/model.py", line 284, in GPT
    log_file: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

https://github.com/hadriansecurity/subwiz/blob/2be210c9482c2eb9002f45c706e2177d3d39a5c7/subwiz/model.py#L284

Steps to reproduce:

```
pip install subwiz
subwiz
```

Environment:
```
Python 3.9.18 (main, Aug 23 2024, 00:00:00) 
[GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] on linux
```

**Comment by klaasmeinke** [comment]
This error was occurring because the new Python type hinting is not compatible with Python 3.9. Type hints have been updated to support Python 3.9.

Fixed in release 0.1.4
